version: '3.8'

services:
  backend:
    build: .
    container_name: steam_reviews_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./scripts:/app/scripts
      - ./datasets:/app/datasets
    environment:
      # Variáveis usadas pelo kaggle via os.environ caso queira injetar do .env
      - KAGGLE_USERNAME=${KAGGLE_USERNAME:-}
      - KAGGLE_KEY=${KAGGLE_KEY:-}
